# Monokai-Pro coding theme (Refined professional dark gray)
set -g status-style bg='#2d2a2e',fg='#ffd866'
set -g status-left '#[bg=#fc9867]#[fg=#221f22]#{?client_prefix,#[bg=#ff6188],}C-a'
set -ga status-left '#[bg='#2d2a2e']#[fg=#ff6188]#{?window_zoomed_flag,#[bg=#ff6188]#[fg=#2d2a2e],} z '
set -g window-status-current-style fg='#221f22',bg='#a9dc76'
set -g window-style bg='#2d2a2e'
set -g window-active-style bg='#221f22'
set -g pane-border-style fg='#403e41',bg='#221f22'
set -g pane-active-border-style fg='#ffd866',bg='#2d2a2e'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#fc9867]#[bold]#{pane_current_path}#[default],#[fg=#727072]#{pane_current_path}#[default]}"
