# Cyberpunk-Neon coding theme (High intensity neon purple/magenta)
set -g status-style bg='#171221',fg='#ff007f'
set -g status-left '#[bg=#00f0ff]#[fg=#0f0b15]#{?client_prefix,#[bg=#ff007f],}C-a'
set -ga status-left '#[bg='#171221']#[fg=#ff007f]#{?window_zoomed_flag,#[bg=#ff007f]#[fg=#171221],} z '
set -g window-status-current-style fg='#0f0b15',bg='#39ff14'
set -g window-style bg='#120e1a'
set -g window-active-style bg='#0f0b15'
set -g pane-border-style fg='#251b35',bg='#0f0b15'
set -g pane-active-border-style fg='#ff007f',bg='#120e1a'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ff007f]#[bold]#{pane_current_path}#[default],#[fg=#251b35]#{pane_current_path}#[default]}"
