# PowerShell theme (Windows PowerShell Classic Deep Navy Blue & Yellow/Cyan)
set -g status-style bg='#011638',fg='#eeedf0'
set -g status-left '#[bg=#ffff00]#[fg=#012456]#{?client_prefix,#[bg=#00a2ed]#[fg=#ffffff],}C-a'
set -ga status-left '#[bg=#011638]#[fg=#ffff00]#{?window_zoomed_flag,#[bg=#ffff00]#[fg=#012456],} z '
set -g window-status-current-style fg='#012456',bg='#00a2ed'
set -g window-style bg='#011b40'
set -g window-active-style bg='#012456'
set -g pane-border-style fg='#0c3a7a',bg='#012456'
set -g pane-active-border-style fg='#ffff00',bg='#011b40'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ffff00]#[bold]#{pane_current_path}#[default],#[fg=#688cb8]#{pane_current_path}#[default]}"
