# Windows Terminal theme (Fluent Dark Campbell #0C0C0C & Windows Accent Blue #0078D7)
set -g status-style bg='#1a1a1a',fg='#cccccc'
set -g status-left '#[bg=#0078d7]#[fg=#ffffff]#{?client_prefix,#[bg=#61d6d6]#[fg=#0c0c0c],}C-a'
set -ga status-left '#[bg=#1a1a1a]#[fg=#61d6d6]#{?window_zoomed_flag,#[bg=#61d6d6]#[fg=#0c0c0c],} z '
set -g window-status-current-style fg='#ffffff',bg='#0078d7'
set -g window-style bg='#161616'
set -g window-active-style bg='#0c0c0c'
set -g pane-border-style fg='#2d2d2d',bg='#0c0c0c'
set -g pane-active-border-style fg='#0078d7',bg='#161616'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#61d6d6]#[bold]#{pane_current_path}#[default],#[fg=#767676]#{pane_current_path}#[default]}"
