# Paper Sepia Theme (E-Ink & Natural Sunlight Reader)
set -g status-style bg='#ede3cb',fg='#433422'
set -g status-left '#[bg=#728954]#[fg=#ffffff]#{?client_prefix,#[bg=#b8543f],}C-a'
set -ga status-left '#[bg=#ede3cb]#[fg=#b8543f]#{?window_zoomed_flag,#[bg=#b8543f]#[fg=#ffffff],} z '
set -g window-status-current-style fg='#ffffff',bg='#b8543f'
set -g window-style bg='#ede3cb'
set -g window-active-style bg='#fbf0d9'
set -g pane-border-style fg='#d4c8ae',bg='#ede3cb'
set -g pane-active-border-style fg='#b8543f',bg='#fbf0d9'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#b8543f]#[bold]#{pane_current_path}#[default],#[fg=#8c7d67]#{pane_current_path}#[default]}"
