# Low-Scatter-Slate Focus theme (Rayleigh Anti-Scatter / High Focus Contrast)
set -g status-style bg='#2c2e35',fg='#cfd3dc'
set -g status-left '#[bg=#9da9be]#[fg=#16171b]#{?client_prefix,#[bg=#d06d64]#[fg=#ffffff],}C-a'
set -ga status-left '#[bg=#2c2e35]#[fg=#8e9cb4]#{?window_zoomed_flag,#[bg=#8e9cb4]#[fg=#16171b],} z '
set -g window-status-current-style fg='#16171b',bg='#cfd3dc',bold
set -g window-style bg='#262830'
set -g window-active-style bg='#101114'
set -g pane-border-style fg='#424654',bg='#262830'
set -g pane-active-border-style fg='#9da9be',bg='#101114'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#e2e5eb]#[bold]#{pane_current_path}#[default],#[fg=#767c8e]#{pane_current_path}#[default]}"
