# Astigmatism-Safe Focus theme (Active/Inactive Contrast & Halation-Proof)
set -g status-style bg='#282c34',fg='#abb2bf'
set -g status-left '#[bg=#e0e0e0]#[fg=#20222c]#{?client_prefix,#[bg=#e06c75],}C-a'
set -ga status-left '#[bg=#282c34]#[fg=#e06c75]#{?window_zoomed_flag,#[bg=#e06c75]#[fg=#282c34],} z '
set -g window-status-current-style fg='#1c1e26',bg='#abb2bf'
set -g window-style bg='#252833'
set -g window-active-style bg='#181920'
set -g pane-border-style fg='#2d3139',bg='#252833'
set -g pane-active-border-style fg='#abb2bf',bg='#181920'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ffffff]#[bold]#{pane_current_path}#[default],#[fg=#5c6370]#{pane_current_path}#[default]}"
