# Fovea-Lutein Focus theme (Macular Carotenoid / Deep Active Split)
set -g status-style bg='#28251e',fg='#ecd29b'
set -g status-left '#[bg=#e5a93b]#[fg=#181714]#{?client_prefix,#[bg=#c25428]#[fg=#ffffff],}C-a'
set -ga status-left '#[bg=#28251e]#[fg=#d4952c]#{?window_zoomed_flag,#[bg=#d4952c]#[fg=#181714],} z '
set -g window-status-current-style fg='#181714',bg='#ecd29b',bold
set -g window-style bg='#24221d'
set -g window-active-style bg='#0e0d0b'
set -g pane-border-style fg='#423d30',bg='#24221d'
set -g pane-active-border-style fg='#e5a93b',bg='#0e0d0b'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ecd29b]#[bold]#{pane_current_path}#[default],#[fg=#807255]#{pane_current_path}#[default]}"
