# One Dark Focus theme (Active/Inactive Pane Contrast)
set -g status-style bg='#21252b',fg='#c678dd'
set -g status-left '#[bg=#61afef]#[fg=#1e2127]#{?client_prefix,#[bg=#e06c75],}C-a'
set -ga status-left '#[bg=#21252b]#[fg=#e06c75]#{?window_zoomed_flag,#[bg=#e06c75]#[fg=#21252b],} z '
set -g window-status-current-style fg='#1e2127',bg='#98c379'
set -g window-style bg='#282c34'
set -g window-active-style bg='#1e2227'
set -g pane-border-style fg='#3e4452',bg='#282c34'
set -g pane-active-border-style fg='#61afef',bg='#1e2227'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#abb2bf]#[bold]#{pane_current_path}#[default],#[fg=#5c6370]#{pane_current_path}#[default]}"
