# Everforest Theme (Naturalist Forest & Eye Relaxation)
set -g status-style bg='#232a2e',fg='#a7c080'
set -g status-left '#[bg=#a7c080]#[fg=#232a2e]#{?client_prefix,#[bg=#e69875],}C-a'
set -ga status-left '#[bg=#232a2e]#[fg=#e69875]#{?window_zoomed_flag,#[bg=#e69875]#[fg=#232a2e],} z '
set -g window-status-current-style fg='#232a2e',bg='#83c092'
set -g window-style bg='#2d353b'
set -g window-active-style bg='#232a2e'
set -g pane-border-style fg='#343f44',bg='#2d353b'
set -g pane-active-border-style fg='#a7c080',bg='#232a2e'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#d3c6aa]#[bold]#{pane_current_path}#[default],#[fg=#7a8478]#{pane_current_path}#[default]}"
