# Kanagawa Focus Theme (Active/Inactive Contrast)
set -g status-style bg='#16161d',fg='#7e9cd8'
set -g status-left '#[bg=#7e9cd8]#[fg=#16161d]#{?client_prefix,#[bg=#ffa066],}C-a'
set -ga status-left '#[bg=#16161d]#[fg=#ffa066]#{?window_zoomed_flag,#[bg=#ffa066]#[fg=#16161d],} z '
set -g window-status-current-style fg='#16161d',bg='#98bb6c'
set -g window-style bg='#1f1f28'
set -g window-active-style bg='#121217'
set -g pane-border-style fg='#2a2a37',bg='#1f1f28'
set -g pane-active-border-style fg='#7e9cd8',bg='#121217'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#dcd7ba]#[bold]#{pane_current_path}#[default],#[fg=#727169]#{pane_current_path}#[default]}"
