# Nord Focus theme (Active/Inactive Pane Contrast)
set -g status-style bg='#3b4252',fg='#88c0d0'
set -g status-left '#[bg=#8fbcbb]#[fg=#2e3440]#{?client_prefix,#[bg=#bf616a],}C-a'
set -ga status-left '#[bg=#3b4252]#[fg=#bf616a]#{?window_zoomed_flag,#[bg=#bf616a]#[fg=#3b4252],} z '
set -g window-status-current-style fg='#2e3440',bg='#a3be8c'
set -g window-style bg='#2e3440'
set -g window-active-style bg='#1e222b'
set -g pane-border-style fg='#3b4252',bg='#2e3440'
set -g pane-active-border-style fg='#88c0d0',bg='#1e222b'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#eceff4]#[bold]#{pane_current_path}#[default],#[fg=#4c566a]#{pane_current_path}#[default]}"
