# Catppuccin Mocha theme
set -g status-style bg='#181825',fg='#cba6f7'
set -g status-left '#[bg=#b4befe]#[fg=#11111b]#{?client_prefix,#[bg=#fab387],}C-a'
set -ga status-left '#[bg=#181825]#[fg=#fab387]#{?window_zoomed_flag,#[bg=#fab387]#[fg=#181825],} z '
set -g window-status-current-style fg='#11111b',bg='#a6e3a1'
set -g window-style bg='#1e1e2e'
set -g window-active-style bg='#181825'
set -g pane-border-style fg='#313244',bg='#181825'
set -g pane-active-border-style fg='#45475a',bg='#1e1e2e'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#cdd6f4]#[bold]#{pane_current_path}#[default],#[fg=#585b70]#{pane_current_path}#[default]}"
