# Dracula Theme (Global S-Tier Dark)
set -g status-style bg='#1e1f29',fg='#bd93f9'
set -g status-left '#[bg=#bd93f9]#[fg=#282a36]#{?client_prefix,#[bg=#ff79c6],}C-a'
set -ga status-left '#[bg=#1e1f29]#[fg=#ffb86c]#{?window_zoomed_flag,#[bg=#ffb86c]#[fg=#282a36],} z '
set -g window-status-current-style fg='#282a36',bg='#50fa7b'
set -g window-style bg='#282a36'
set -g window-active-style bg='#1e1f29'
set -g pane-border-style fg='#44475a',bg='#282a36'
set -g pane-active-border-style fg='#bd93f9',bg='#1e1f29'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ff79c6]#[bold]#{pane_current_path}#[default],#[fg=#6272a4]#{pane_current_path}#[default]}"
