# Tokyonight Focus theme (Active/Inactive Pane Contrast)
set -g status-style bg='#16161e',fg='#a9b1d6'
set -g status-left '#[bg=#7aa2f7]#[fg=#16161e]#{?client_prefix,#[bg=#f7768e],}C-a'
set -ga status-left '#[bg='#16161e']#[fg=#f7768e]#{?window_zoomed_flag,#[bg=#f7768e]#[fg=#16161e],} z '
set -g window-status-current-style fg='#16161e',bg='#9ece6a'
set -g window-style bg='#1a1b26'
set -g window-active-style bg='#0f1017'
set -g pane-border-style fg='#292e42',bg='#1a1b26'
set -g pane-active-border-style fg='#7aa2f7',bg='#0f1017'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#c0caf5]#[bold]#{pane_current_path}#[default],#[fg=#565f89]#{pane_current_path}#[default]}"
