# Rose Pine Focus theme (Active/Inactive Pane Contrast)
set -g status-style bg='#1f1d2e',fg='#e0def4'
set -g status-left '#[bg=#ebbc89]#[fg=#191724]#{?client_prefix,#[bg=#eb6f92],}C-a'
set -ga status-left '#[bg='#1f1d2e']#[fg=#eb6f92]#{?window_zoomed_flag,#[bg=#eb6f92]#[fg=#1f1d2e],} z '
set -g window-status-current-style fg='#191724',bg='#f6c177'
set -g window-style bg='#191724'
set -g window-active-style bg='#12101a'
set -g pane-border-style fg='#26233a',bg='#191724'
set -g pane-active-border-style fg='#eb6f92',bg='#12101a'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#e0def4]#[bold]#{pane_current_path}#[default],#[fg=#6e6a86]#{pane_current_path}#[default]}"
