# Gruvbox theme (Evergreen Reddit Retro Clay/Gold)
set -g status-style bg='#3c3836',fg='#ebdbb2'
set -g status-left '#[bg=#fabd2f]#[fg=#282828]#{?client_prefix,#[bg=#fb4934],}C-a'
set -ga status-left '#[bg='#3c3836']#[fg=#fb4934]#{?window_zoomed_flag,#[bg=#fb4934]#[fg=#3c3836],} z '
set -g window-status-current-style fg='#282828',bg='#b8bb26'
set -g window-style bg='#282828'
set -g window-active-style bg='#3c3836'
set -g pane-border-style fg='#504945',bg='#3c3836'
set -g pane-active-border-style fg='#a89984',bg='#282828'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ebdbb2]#[bold]#{pane_current_path}#[default],#[fg=#7c6f64]#{pane_current_path}#[default]}"
