# Ubuntu Aubergine Theme (Canonical Linux Heritage)
set -g status-style bg='#1e0014',fg='#e95420'
set -g status-left '#[bg=#e95420]#[fg=#ffffff]#{?client_prefix,#[bg=#efb73e],}C-a'
set -ga status-left '#[bg=#1e0014]#[fg=#efb73e]#{?window_zoomed_flag,#[bg=#efb73e]#[fg=#1e0014],} z '
set -g window-status-current-style fg='#ffffff',bg='#77216f'
set -g window-style bg='#300a24'
set -g window-active-style bg='#1e0014'
set -g pane-border-style fg='#5e2750',bg='#300a24'
set -g pane-active-border-style fg='#e95420',bg='#1e0014'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ffffff]#[bold]#{pane_current_path}#[default],#[fg=#aea79f]#{pane_current_path}#[default]}"
