# Retro CRT Phosphor Amber (TCO European Standard)
set -g status-style bg='#0a0400',fg='#ffb000'
set -g status-left '#[bg=#ffb000]#[fg=#0a0400]#{?client_prefix,#[bg=#ffcc33],}C-a'
set -ga status-left '#[bg=#0a0400]#[fg=#ffb000]#{?window_zoomed_flag,#[bg=#ffb000]#[fg=#0a0400],} z '
set -g window-status-current-style fg='#0a0400',bg='#ffb000'
set -g window-style bg='#140a02'
set -g window-active-style bg='#0a0400'
set -g pane-border-style fg='#331a00',bg='#140a02'
set -g pane-active-border-style fg='#ffb000',bg='#0a0400'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#ffb000]#[bold]#{pane_current_path}#[default],#[fg=#805800]#{pane_current_path}#[default]}"
