# Retro CRT Phosphor Green (Matrix & VT220 Terminal)
set -g status-style bg='#050805',fg='#33ff33'
set -g status-left '#[bg=#33ff33]#[fg=#050805]#{?client_prefix,#[bg=#00ff66],}C-a'
set -ga status-left '#[bg=#050805]#[fg=#33ff33]#{?window_zoomed_flag,#[bg=#33ff33]#[fg=#050805],} z '
set -g window-status-current-style fg='#050805',bg='#1ee81e'
set -g window-style bg='#0d130d'
set -g window-active-style bg='#050805'
set -g pane-border-style fg='#143314',bg='#0d130d'
set -g pane-active-border-style fg='#33ff33',bg='#050805'
set -g status-right ""
set -g pane-border-format "#{?pane_active,#[fg=#33ff33]#[bold]#{pane_current_path}#[default],#[fg=#198019]#{pane_current_path}#[default]}"
